Add `retryCount` to persistent subscription events
EventStore/EventStore-Client-NodeJS pull request #297
Opened 2022-07-05 12:47 UTC by George-Payne

- Add `PersistentSubscriptionToStreamResolvedEvent` and `PersistentSubscriptionToAllResolvedEvent` types
- Update `PersistentSubscriptionToStream` and `PersistentSubscriptionToAll` types
- Split apart event converter function types
- Add converters for persistent subscritions
- Use new types in `ReadStream`, `Subscription`, and `PersistentSubscriptionImpl`
- Use new converters in `subscribeToPersistentSubscriptionToStream` and `subscribeToPersistentSubscriptionToAll`
- Add tests for `retryCount` in `subscribeToPersistentSubscriptionToStream` and `subscribeToPersistentSubscriptionToAll`
- Update samples to show `retryCount`

2022-07-07 11:22 UTC, ylorph commented on src/types/events.ts
> + * A structure representing a single event or an resolved link event.
maybe add something about being a single / link for persistent subscription ?

2022-07-07 13:28 UTC, YoEight approved these changes

2022-07-11 09:32 UTC, George-Payne commented on src/types/events.ts
> + * A structure representing a single event or an resolved link event.
```suggestion
 * A structure representing a single event or a resolved link event from a persistent subscription.
```

2022-07-11 10:58 UTC, jageall requested changes
Does this need a breaking change / major version label? other than that looks ok to me

2022-07-11 11:07 UTC, George-Payne commented
> Does this need a breaking change / major version label? other than that looks ok to me

Should be fully backwards compatible, `PersistentSubscriptionToStreamResolvedEvent` extends `ResolvedEvent` so can be used everywhere that a `ResolvedEvent` was previously used. 

The only signature with a breaking change is `ConvertGrpcEvent`, which is internal (The type used to describe a function that converts an event from raw GRPC to the returned object).

2022-07-11 13:15 UTC, ylorph approved these changes

2022-07-12 12:21 UTC, merged